version: "3.5"

services:
  app:
    build: .
    container_name: app_event_dispatcher
    volumes:
      - .:/go/src/
    ports:
      - 4500:4500
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
